### ISSUE TITLE
Readme missing

### ISSUE THREAD

**Issue by wallish** [dakshhmehta/abstract-laravel-starter-kit#1]
Hello,

I would like to try your package, can you do a readme please.

Thank you

**Comment by dakshhmehta** [comment]
Hello,

Sorry for late reply..

Sure , Its is available, I am updating it with docs.

For now, its pretty easy and you can require it in your repository and then add the service provider.

I am writing the detailed documentation..

**Comment by dakshhmehta** [comment]
Hello,

The docs has been added in the repository with installation instructions.

I tried my best to have the installation clear as much as possible.

And this is still in development for my internal projects, so there might be any bugs you may find. I will very much appreciate if you report it as soon as you find.

Additionally, feel free to reach me to dakshhmehta@gmail.com for more support.

**Comment by wallish** [comment]
Great Thanks
